version: '3.8'

services:
  flask-app:
    build:
      context: ./app  # Путь к контексту с Dockerfile для Flask приложения
      dockerfile: Dockerfile_flask  # Имя Dockerfile для Flask приложения
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db

  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile_mysql  # Имя Dockerfile для MySQL сервера
    ports:
      - "3306:3306"
    volumes:
      - ./db_config.sql:/docker-entrypoint-initdb.d/db_config.sql  # Путь к SQL скрипту

volumes:
  mysql_data:  # Опционально: для сохранения данных MySQL между перезапусками контейнера
